/**
 * Luxurio Home — Database Seed
 *
 * Populates the DB with:
 *  1. Super-admin account
 *  2. All categories + products from prisma/seed-data.json
 *     (generated by running the scraper, then exporting with export-seed-data.js)
 *
 * Run with:
 *   npx prisma db seed
 */

import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { createRequire } from 'module';
import 'dotenv/config';

const require = createRequire(import.meta.url);
const { categories, products } = require('./seed-data.json');
const prisma = new PrismaClient();

async function main() {
  // ── 1. Super admin ────────────────────────────────────────────────────────
  const email = process.env.ADMIN_EMAIL || 'admin@luxurio.local';
  const password = process.env.ADMIN_PASSWORD || 'admin123';
  const hash = await bcrypt.hash(password, 10);

  await prisma.admin.upsert({
    where: { email },
    update: { role: 'SUPER_ADMIN' },
    create: { email, password: hash, name: 'Founder', role: 'SUPER_ADMIN' },
  });
  console.log('✓ Admin:', email);

  // ── 2. Categories (parents first, then children) ──────────────────────────
  const parents = categories.filter(c => !c.parentId);
  const children = categories.filter(c => c.parentId);

  for (const c of parents) {
    await prisma.category.upsert({
      where: { slug: c.slug },
      update: { name: c.name },
      create: { id: c.id, name: c.name, slug: c.slug, parentId: null },
    });
  }
  for (const c of children) {
    await prisma.category.upsert({
      where: { slug: c.slug },
      update: { name: c.name, parentId: c.parentId },
      create: { id: c.id, name: c.name, slug: c.slug, parentId: c.parentId },
    });
  }
  console.log('✓ Categories:', categories.length);

  // ── 3. Products ───────────────────────────────────────────────────────────
  let created = 0, skipped = 0;
  for (const prod of products) {
    const exists = await prisma.product.findUnique({ where: { slug: prod.slug } });
    if (exists) { skipped++; continue; }

    await prisma.product.create({
      data: {
        id: prod.id,
        name: prod.name,
        slug: prod.slug,
        description: prod.description,
        price: prod.price,
        stock: prod.stock,
        published: prod.published,
        featured: prod.featured,
        categoryId: prod.categoryId,
        material: prod.material || null,
        dimensions: prod.dimensions || null,
        images: {
          create: prod.images.map(img => ({ url: img.url, order: img.order })),
        },
      },
    });
    created++;
  }
  console.log('✓ Products created:', created, '/ skipped (already exist):', skipped);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
